### PR TITLE
Fix not continuing headings over newlines

### PR DESCRIPTION
**Pull request by bananaoomarang**
Fixes https://github.com/natejenkins/socialApp/issues/3946

### CODE REVIEW

**Comment by DZGoldman** [comment]
confused about where this branch is coming from - are you working on a separate fork or something?

**Comment by bananaoomarang** [comment]
yeah, I forked it to my profile, if @natejenkins adds me I can push to a branch here

**Comment by bananaoomarang** [comment]
https://github.com/bananaoomarang/squire/tree/fix-heading-newling

**Comment by DZGoldman** [comment]
Ah I see. Yeah, I just wanted to test out your branch.

**Comment by bananaoomarang** [comment]
Yeah, I think right now you'll need to clone/yarn link my version

**Pull request merged**
