### PR TITLE
Fix non-editable regression

### PR DESCRIPTION
**Pull request by DZGoldman**
Fixes https://github.com/natejenkins/socialApp/issues/3167
Switching from doc's ```getSelection``` to squire's here https://github.com/natejenkins/squire/pull/43 caused the regression with moving out of non-editable nodes. 

The range object they return are slightly different - doc's has the start/end container as the text node, squire's has it as the non-editable node (span, say). ```moveNodeOutOfNotEditable``` doesn't handle the later correctly, since it starts its search with the starting node's parent, not the node itself. 

An alternative fix would be to modify ```moveNodeOutOfNotEditable``` to handle this case; this here fix is quicker.

### CODE REVIEW

**Comment by dginev** [comment]
[Fragility PSA] Regression tests needed for long-term stability

**Comment by DZGoldman** [comment]
Agreed. Was just trying to write a click-test for this; can't seem to get a convincing enough simulation of the click event to trigger the bug using our pure html/js tests. Headless browser - I think it's high-time.

**Comment by DZGoldman** [comment]
@jmnicholson this fixes your equation troubles (they are currently impossible to delete)

**Comment by DZGoldman** [comment]
> Pointing at a non-editable node is a perfectly valid cursor position which you can explore with the keyboard.

This was what I  misunderstood - thanks for the explanation!

**Pull request merged**
