### PR TITLE
Sanitization for headers and divs (updated)

### PR DESCRIPTION
**Pull request by DZGoldman**
Ensure headers have no unwanted tags nested inside them - `/^(?:B|DIV|H1|H2|H3|UL|OL|LI|TABLE)$/;`

This cleans up some of these cases: https://github.com/natejenkins/socialApp/issues/3702, and generally gets one step closer to the cleaner forcing conformity to the spec. Shows the general format we can use in the cleaner for conditionally unwrapping elements depending on how they are nested. Nested `divs` more generally is next...

### CODE REVIEW

**Comment by DZGoldman** [comment]
The eternal squire PR dilema - high in value, low in anyone's desire to review.

**Comment by DZGoldman** [comment]
(rebased)

**Comment by DZGoldman** [comment]
bump

**Comment by jmnicholson** [comment]
I cleaned up the article manually by deleting the problematic block and repasting it. lol.

**Comment by jmnicholson** [comment]
@natejenkins bump!!!!

**Comment by DZGoldman** [comment]
rebased (with ignored build files)

**Pull request merged**
